name: amazing-search-bar
version: 0.1.0.0
homepage: https://github.com/satosystems/amazing-search-bar#readme
license: BSD3
author: Satoshi Ogata
maintainer: satosystems@gmail.com
copyright: 2023 Satoshi Ogata
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show

executables:
  amazing-search-bar:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -fwarn-incomplete-patterns
      - -threaded
